#include "layers.h"

#include <lib/metal4/context.h>
#include <lib/metal4/device.h>
#include <lib/metal4/allocation.h>
#include <lib/metal4/textures.h>
#include <lib/metal4/pipelines.h>
#include <lib/metal4/queue.h>
#include <lib/metal4/command_buffers.h>
#include <lib/metal4/semaphores.h>
#include <lib/metal4/depthstencilstates.h>
#include <lib/metal4/blend_states.h>
#include <lib/metal4/validation.h>

GpuBaseLayer gMtl4BaseLayer = {
	/*layerInit=*/			mtl4Init,
	/*gpuDeinit=*/			mtl4Deinit,
	/*gpuEnumerateDevices=*/	mtl4EnumerateDevices,
	/*gpuSelectDevice=*/		mtl4SelectDevice,
	/*gpuMalloc=*/			mtl4Malloc,
	/*gpuFree=*/			mtl4Free,
	/*gpuHostToDevicePointer=*/	mtl4HostToDevicePointer,
	/*gpuTextureSizeAlign=*/	mtl4TextureSizeAlign,
	/*gpuCreateTexture=*/		mtl4CreateTexture,
	/*gpuTextureViewDescriptor=*/	mtl4TextureViewDescriptor,
	/*gpuRWTextureViewDescriptor=*/	mtl4RWTextureViewDescriptor,
	/*gpuCreateComputePipeline=*/	mtl4CreateComputePipeline,
	/*gpuCreateRenderPipeline=*/	mtl4CreateRenderPipeline,
	/*gpuCreateMeshletPipeline=*/	mtl4CreateMeshletPipeline,
	/*gpuFreePipeline=*/		mtl4FreePipeline,
	/*gpuCreateDepthStencilState=*/	mtl4CreateDepthStencilState,
	/*gpuCreateBlendState=*/	mtl4CreateBlendState,
	/*gpuFreeDepthStencilState=*/	mtl4FreeDepthStencilState,
	/*gpuFreeBlendState=*/		mtl4FreeBlendState,
	/*gpuCreateQueue=*/		mtl4CreateQueue,
	/*gpuStartCommandEncoding=*/	mtl4StartCommandEncoding,
	/*gpuSubmit=*/			mtl4Submit,
	/*gpuSubmitWithSignal=*/	mtl4SubmitWithSignal,
	/*gpuCreateSemaphore=*/		mtl4CreateSemaphore,
	/*gpuWaitSemaphore=*/		mtl4WaitSemaphore,
	/*gpuDestroySemaphore=*/	mtl4DestroySemaphore,
	/*gpuMemCpy=*/			mtl4MemCpy,
	/*gpuCopyToTexture=*/		mtl4CopyToTexture,
	/*gpuCopyFromTexture=*/		mtl4CopyFromTexture,
	/*gpuSetActiveTextureHeapPtr=*/	mtl4SetActiveTextureHeapPtr,
	/*gpuBarrier=*/			mtl4Barrier,
	/*gpuSignalAfter=*/		mtl4SignalAfter,
	/*gpuWaitBefore=*/		mtl4WaitBefore,
	/*gpuSetPipeline=*/		mtl4SetPipeline,
	/*gpuSetDepthStencilState=*/	mtl4SetDepthStencilState,
	/*gpuSetBlendState=*/		mtl4SetBlendState,
	/*gpuDispatch=*/		mtl4Dispatch,
	/*gpuDispatchIndirect=*/	mtl4DispatchIndirect,
};

GpuLayer gMtl4ValidationLayer = {
	/*layerInit=*/			nullptr,
	/*gpuDeinit=*/			nullptr,
	/*gpuEnumerateDevices=*/	mtl4ValidateEnumerateDevices,
	/*gpuSelectDevice=*/		mtl4ValidateSelectDevice,
	/*gpuMalloc=*/			mtl4ValidateGpuMalloc,
	/*gpuFree=*/ 			nullptr,
	/*gpuHostToDevicePointer=*/	mtl4ValidateGpuHostToDevicePointer,
	/*gpuTextureSizeAlign=*/	mtl4ValidateGpuTextureSizeAndAlign,
	/*gpuCreateTexture=*/		mtl4ValidateGpuCreateTexture,
	/*gpuTextureViewDescriptor=*/	mtl4ValidateGpuTextureViewDescriptor,
	/*gpuRWTextureViewDescriptor=*/	mtl4ValidateGpuTextureRWViewDescriptor,
	/*gpuCreateComputePipeline=*/	nullptr,
	/*gpuCreateRenderPipeline=*/	nullptr,
	/*gpuCreateMeshletPipeline=*/	nullptr,
	/*gpuFreePipeline=*/		nullptr,
	/*gpuCreateDepthStencilState=*/	nullptr,
	/*gpuCreateBlendState=*/	nullptr,
	/*gpuFreeDepthStencilState=*/	nullptr,
	/*gpuFreeBlendState=*/		nullptr,
	/*gpuCreateQueue=*/		nullptr,
	/*gpuStartCommandEncoding=*/	nullptr,
	/*gpuSubmit=*/			nullptr,
	/*gpuSubmitWithSignal=*/	nullptr,
	/*gpuCreateSemaphore=*/		nullptr,
	/*gpuWaitSemaphore=*/		nullptr,
	/*gpuDestroySemaphore=*/	nullptr,
	/*gpuMemCpy=*/			nullptr,
	/*gpuCopyToTexture=*/		nullptr,
	/*gpuCopyFromTexture=*/		nullptr,
	/*gpuSetActiveTextureHeapPtr=*/	nullptr,
	/*gpuBarrier=*/			nullptr,
	/*gpuSignalAfter=*/		mtl4ValidateGpuSignalAfter,
	/*gpuWaitBefore=*/		mtl4ValidateGpuWaitBefore,
	/*gpuSetPipeline=*/		nullptr,
	/*gpuSetDepthStencilState=*/	nullptr,
	/*gpuSetBlendState=*/		nullptr,
	/*gpuDispatch=*/		nullptr,
	/*gpuDispatchIndirect=*/	nullptr,
};

